### ISSUE TITLE
LateInitializationError: Field 'idToken' has not been initialized.

### ISSUE THREAD

**Issue by alaaNabil24** [sultan-algarbi-paylink/paylink-flutter-package#2]
LateInitializationError: Field 'idToken' has not been initialized.

how can fix this  ?

**Comment by sultan-algarbi** [comment]
The `LateInitializationError: Field 'idToken' has not been initialized` message shouldn’t be an issue in this code, as `idToken` is declared as a nullable (`String?`). By default, a nullable variable is `null` if not initialized, so there’s no need for an initial value.

If the error persists, it’s likely that there’s confusion from Dart’s analyzer or some other part of the codebase might be unintentionally accessing `idToken` in a way that expects a non-nullable type. However, the code here is correctly handling `idToken` as nullable and shouldn’t raise an initialization error.

**Note: Make sure you use the latest version of this package**

**Comment by ghost** [comment]
The `LateInitializationError: Field 'idToken' has not been initialized` message shouldn’t be an issue in this code, as `idToken` is declared as a nullable (`String?`). By default, a nullable variable is `null` if not initialized, so there’s no need for an initial value.

If the error persists, it’s likely that there’s confusion from Dart’s analyzer or some other part of the codebase might be unintentionally accessing `idToken` in a way that expects a non-nullable type. However, the code here is correctly handling `idToken` as nullable and shouldn’t raise an initialization error.

**Note: Make sure you use the latest version of this package**
