### ISSUE TITLE
Unhandled Exception: type 'List<dynamic>' is not a subtype of type 'List<Map<String, dynamic>>?' in type cast

### ISSUE THREAD

**Issue by ahmad-dev-iks** [sultan-algarbi-paylink/paylink-flutter-package#3]
I am facing an error in the provided example code. Here is the complete error log:

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: type 'List<dynamic>' is not a subtype of type 'List<Map<String, dynamic>>?' in type cast
E/flutter (10012): #0      new PaylinkGatewayOrderRequest.fromMap (package:paylink_payment/models/paylink_gateway_order_request.dart:42:27)
E/flutter (10012): #1      new PaylinkInvoice.fromResponseData (package:paylink_payment/models/paylink_invoice.dart:39:38)
E/flutter (10012): #2      PaylinkAPI.addInvoice (package:paylink_payment/api/paylink_api.dart:167:29)
E/flutter (10012): <asynchronous suspension>
E/flutter (10012): #3      _PaylinkTestPageState.addPendingInvoiceForTesting (package:example/presentation/pages/paylink_test_page.dart:169:26)
E/flutter (10012): <asynchronous suspension>
E/flutter (10012): 

It occurs when below code is executed:
paylink.addInvoice(
      amount: 180.0,
      clientMobile: '0512345678',
      clientName: 'Mohammed',
      orderNumber: '123456789',
      callBackUrl: 'https://example.com',
      products: [],
    ).then(
          (invoiceDetails) => addInvoiceToList(invoiceDetails, false),
    );

**Comment by ghost** [comment]
Thank you for reporting this issue! We identified that the error was caused by the fromMap constructor expecting a List<Map<String, dynamic>> for the products field, while receiving a generic List instead. We've updated the constructor to handle List<dynamic> more flexibly, casting each element appropriately to avoid runtime errors.

This fix should resolve the issue. Please pull the latest version and let us know if the problem persists!

**Comment by ahmad-dev-iks** [comment]
> Thank you for reporting this issue! We identified that the error was caused by the fromMap constructor expecting a List<Map<String, dynamic>> for the products field, while receiving a generic List instead. We've updated the constructor to handle List more flexibly, casting each element appropriately to avoid runtime errors.
> 
> This fix should resolve the issue. Please pull the latest version and let us know if the problem persists!

Thanks @sultan-algarbi-paylink for the quick response, The issue has been fixed.
