### ISSUE TITLE
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: FormatException: Unexpected end of input (at character 1)

### ISSUE THREAD

**Issue by ahmad-dev-iks** [sultan-algarbi-paylink/paylink-flutter-package#4]
In the provided example code, i am getting following error:
E/flutter ( 9562): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: FormatException: Unexpected end of input (at character 1)
E/flutter ( 9562): 
E/flutter ( 9562): ^
E/flutter ( 9562): 
E/flutter ( 9562): #0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1465:5)
E/flutter ( 9562): #1      _ChunkedJsonParser.close (dart:convert-patch/convert_patch.dart:499:7)
E/flutter ( 9562): #2      _parseJson (dart:convert-patch/convert_patch.dart:37:10)
E/flutter ( 9562): #3      JsonDecoder.convert (dart:convert/json.dart:610:36)
E/flutter ( 9562): #4      JsonCodec.decode (dart:convert/json.dart:216:41)
E/flutter ( 9562): #5      PaylinkAPI.addInvoice (package:paylink_payment/api/paylink_api.dart:161:33)
E/flutter ( 9562): <asynchronous suspension>
E/flutter ( 9562): #6      _PaylinkTestPageState.addPendingInvoiceForTesting.<anonymous closure> (package:example/presentation/pages/paylink_test_page.dart:186:11)
E/flutter ( 9562): <asynchronous suspension>
E/flutter ( 9562): 

This error occurs when following line of code executed:
paylink.addInvoice(
      amount: 180.0,
      clientMobile: '0512345678',
      clientName: 'Mohammed',
      orderNumber: '1234567899',
      callBackUrl: 'https://example.com',
      products: [],
    ).then(
          (invoiceDetails) => addInvoiceToList(invoiceDetails, false),
    );
    
   and the **"PaylinkAPI.addInvoice (package:paylink_payment/api/paylink_api.dart:161:33)"** points to
    final orderDetails = json.decode(response.body);

**Comment by ghost** [comment]
The issue does not lie within the package itself; however, to handle additional cases, we’ve implemented some improvements in the new version (2.0.2):

- Removed the `late` keyword from `idToken` to address initialization issues.
- Added a check for empty responses to ensure proper handling when `response.body` is empty.

These changes should help resolve the issue you’re encountering.
